name = "afip-api"
main = "src/index.ts"
compatibility_date = "2024-04-15"

[vars]
ENV = "development"

# Secrets a configurar via:
# wrangler secret put PUBLIC_API_KEY
# wrangler secret put INTERNAL_API_KEY
# wrangler secret put AFIP_SERVICE_URL